FROM node:24-alpine

RUN apk add --no-cache libc6-compat

ENV PNPM_HOME="/root/.local/share/pnpm"
ENV PATH="${PATH}:${PNPM_HOME}"

RUN corepack enable && corepack prepare pnpm@latest --activate

RUN npm install -g @nestjs/cli

WORKDIR /usr/src/app

EXPOSE 3000
EXPOSE 9229

CMD ["tail", "-f", "/dev/null"]